POST http://localhost:8080/api/player
Content-Type: application/json

{
  "firstname": "Valentin",
  "lastname": "Weinhäupl",
  "fk_agelevelid": 5,
  "goals": 2,
  "position": "Stuermer"
}

###
GET http://localhost:8080/api/player

###
GET http://localhost:8080/api/player/1

###
GET http://localhost:8080/api/player/firstlast?first=John&last=Doe

###
DELETE http://localhost:8080/api/player/1