GET http://localhost:8080/api/player

###
POST http://localhost:8080/api/player
Content-Type: application/json

{
  "firstname": "Valentin",
  "lastname": "Weinhaeupl",
  "position" : "Stuermer"
}

###
GET http://localhost:8080/api/player/1

###
POST http://localhost:8080/api/field
Content-Type: application/json

{
  "location": "Bruckmühl"
}

###

DELETE http://localhost:8080/api/field/1

###
POST http://localhost:8080/api/agelevel
Content-Type: application/json

{
  "ageLevelName": "U10"
}

###
GET http://localhost:8080/api/agelevel/1

###

